In [ ]:
# Merging aur Joining DataFrames

In [1]:
import pandas as pd

In [ ]:
# Step 1: Read CSV Files

In [8]:
df1 = pd.read_csv('Housing.csv')

In [9]:
df1

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [10]:
df2 = pd.read_csv('Owners.csv')

In [11]:
df2

      first      last        address      city       phone
0      Jane    Garcia    643 2nd Ave    Boston  9325763815
1      Emma     Smith  5399 Maple St   Houston  9084802186
2       Bob     Smith  5016 Cedar St    Boston  8985554810
3     Alice     Brown   3417 1st Ave  San Jose  2684754835
4    Olivia    Miller    4543 Oak St  San Jose  2339613320
..      ...       ...            ...       ...         ...
495     Bob  Martinez  2070 Broadway    Dallas  2613112172
496     Bob     Davis    3017 Oak St    Dallas  9558994821
497    John  Martinez   4471 Main St    Austin  5995458733
498   David     Smith  7427 Cedar St   Chicago  3295918401
499    Emma     Smith   3791 Main St    Dallas  6622608358

[500 rows x 5 columns]

In [ ]:
# Step 2: Merge DataFrames

In [15]:
result = df1.join(df2)
print(result)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus  \
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

      first    last        address      city         phone
0      Jane  Garcia    643 2nd Ave    Boston  9.325764e+09
1      Emma   Smith  5399 Maple St   Houston  9.084802e+09
2       Bob   Smith  5016 Cedar St    Boston  8.985555e+09
3     Alice   Brown   3417 1st Ave  San Jose  2.684755e+09
4    Olivia  Miller    4543 Oak St  San Jose  2.339613e+09
..      ...     ...            ...       ...           ...
540     NaN     NaN            NaN       NaN           NaN
541     NaN     NaN            NaN       NaN           NaN
542     NaN     NaN            NaN       NaN           NaN
543     NaN     NaN            NaN       NaN           NaN
544     NaN     NaN            NaN       NaN           NaN

[545 rows x 18 columns]